eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
server:
  port: 8082
spring:
  application:
    name: Hotel-Service
  datasource:
    password: postgres
    url: jdbc:postgresql://localhost:5432/microServices
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


# okta configuration

okta:
  oauth2:
    issuer: https://dev-56783183.okta.com/oauth2/default
    audience:  api://default   